### ISSUE TITLE
Epic: Benchmark against Circom (Groth16)

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/zk_bench#4]
### Problem

We don't currently have comprehensive and objective insights into how Noir performs against other ZK tech stacks.

### Happy case

```[tasklist]
### Standard Libraries
- [ ] Gather benchmark numbers on Nargo
- [ ] Gather benchmark numbers on NoirJS
- [ ] Gather benchmark numbers on snarkjs
```

```[tasklist]
### Semaphore
- [ ] Gather benchmark numbers on Nargo
- [ ] Gather benchmark numbers on NoirJS
```

Benchmarks should be conducted both for 1 and large number (e.g. 100) of iterations to put UltraPlonk's lookup table fixed cost into perspective.

### References

- Crypto team's benchmarking script: https://github.com/AztecProtocol/aztec-packages/blob/master/barretenberg/cpp/scripts/benchmark_wasm_remote.sh
- Ze's NoirJS vs Circom Semaphore benchmarks: https://zpedro.notion.site/Semaphore-ad21b26922e442c6b988695717a108b1#e61659ceb7c04c09909c4902f2fbdac3
- Savio's Nargo v0.21.0 benchmarks: https://github.com/Savio-Sou/noir-benchmarks
- Community's Polylang vs Miden vs Risc0 vs Noir vs Leo benchmarks: https://zkbench.dev/
